version: '2.2'
services:
    app:
      container_name: free_tree_app
      restart: always
      build: ./
      command: bash -c "npm install && node app.js"
      volumes:
        - .:/usr/src/app/
      ports:
        - 3000:3000
      links:
        - database
    database:
      container_name: free_tree_database
      image: mongo:latest
      volumes:
        - ./data:/data/db
      ports:
        - "27017:27017"
      environment:
        - MONGODB_ADMIN_USER=root
        - MONGODB_ADMIN_PASS=pass