version: '2.2'
services:
    app:
      container_name: free_trees_app
      restart: always
      build: ./
      volumes:
        - .:/usr/src/app/
        - /usr/src/app/node_modules
      ports:
        - 3000:3000
      links:
        - database
    database:
      container_name: free_trees_database
      image: mongo:4.2-bionic
      volumes:
        - ./data:/data/db
      ports:
        - "27017:27017"
      environment:
        - MONGODB_ADMIN_USER=root
        - MONGODB_ADMIN_PASS=pass
